#!/bin/bash -
#
# scoyo GmbH Virtuozzo HA IP Script
#
#   Copyright [2008] [scoyo GmbH]
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
#
#  Author: Lukas Loesche <lukas.loesche@scoyo.com>
#  $LastChangedDate: 2008-10-31 16:04:47 +0100 (Fri, 31 Oct 2008) $
#  $LastChangedBy: lukas $
#  $LastChangedRevision: 1535 $
#

\unalias -a
hash -r
ulimit -H -c 0 --

export VEID

if [[ "$0" =~ "^(.*)(umount)$" ]]
then
	MOUNT_SCRIPT="${BASH_REMATCH[1]}mount"

	if [ -x "$MOUNT_SCRIPT" ]
	then
		echo Stopping ha ip daemon
		"$MOUNT_SCRIPT" stop
	else
		echo "couldn't find mount script or it's not executable $MOUNT_SCRIPT... doing nothing"
	fi
else
	echo "don't know how to find my mount script based on $0"
fi

exit 0
